# This is a basic workflow to help you get started with Actions

name: DEX Integration

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the alpha branch
on:
  push:
    branches: [alpha, master]
  pull_request:
    branches: [alpha, master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Testing
        run: |
          command -v solana

          if [ ! -x $(command -v solana) ]; then
            echo "solana not found 1"
          fi

          if ! [ -x $(command -v solana) ]; then
            echo "solana not found 2"
          fi

          exit 1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install pipenv
        uses: dschep/install-pipenv-action@v1

      - name: Install test dependencies
        run: pipenv install --skip-lock pytest

      - name: Run integration tests
        run: scripts/run_int_tests.sh
